const COVER_SIZE = 256
const WATERMARK_SIZE = 32

// Redux Actions
const ACTION_SET_COVER_IMAGE = 'SET_COVER_IMAGE'
const ACTION_SET_WATERMARK = 'SET_WATERMARK'
const ACTION_SET_WATERMARKED_IMAGE_PIXEL = 'SET_WATERMARKED_IMAGE_PIXEL'
const ACTION_SET_EDITED_WATERMARKED_IMAGE_PIXEL = 'SET_EDITED_WATERMARKED_IMAGE_PIXEL'
const ACTION_SET_EXTRACTED_WATERMARK = 'SET_EXTRACTED_WATERMARK'

export {
  COVER_SIZE,
  WATERMARK_SIZE,
  
  ACTION_SET_COVER_IMAGE,
  ACTION_SET_WATERMARK,
  ACTION_SET_WATERMARKED_IMAGE_PIXEL,
  ACTION_SET_EDITED_WATERMARKED_IMAGE_PIXEL,
  ACTION_SET_EXTRACTED_WATERMARK,
}